### ISSUE TITLE
change of repo purpose...

### ISSUE THREAD

**Issue by danielskatz** [rseng/rse-manifesto#1]
What happened to the useful glossary that I thought we were trying to collaboratively build?  This seems to have instead turned into a manifesto, which is also a fine idea to build, but not to me in place of the glossary.

**Comment by vsoch** [comment]
Nothing, it’s a different repository.

**Comment by vsoch** [comment]
https://github.com/USRSE/rse-glossary

**Comment by danielskatz** [comment]
I see - I was confused because the commit history starts with the glossary history, then wipes it out and changes.  So I am listed as a contributor, though I haven't actually contributed to this repo.

I guess this is just a consequence of cloning a repo and then repurposing the clone.

**Comment by vsoch** [comment]
Yep, I wanted the same template, and thought it would be important to preserve the git history.
